### ISSUE TITLE
[SUGGESTION] Xerces Blue variant

### ISSUE THREAD

**Issue by Sunconure11** [DakotaPride/Pride-Moths#1]
Seeing you put down a variant based on a real butterfly, perhaps another could be added. Unless this would appear too similar to the Palos Verde Blue.

**Comment by DakotaPride** [comment]
I wanted the "Palos Verde Blue" variant to be a unique and rare thing, as a one-off. While I do plan on implementing more unique variations in the future, there is no guarantee that the "Xerces Blue" will be added unfortunately. Though, thank you for the suggestion and it will be taken into account forwarding the development of "Happy Pride Moth!"

Let me know if you have any other suggestions or questions relating to the mod!
