### ISSUE TITLE
[ISSUE] Possible incompatibility issue with Quilt

### ISSUE THREAD

**Issue by Sunconure11** [DakotaPride/Pride-Moths#2]
https://gist.github.com/Sunconure11/7a10bbf66d91eb57f7bc6efb5b79a94c

**Comment by DakotaPride** [comment]
Should be fixed now, re-download the jar file for 1.3+1.19.2

**Comment by Sunconure11** [comment]
Testing now.

**Comment by DakotaPride** [comment]
Let me know if it does/doesn't work

**Comment by Sunconure11** [comment]
Noticing a crash, but it is one that is unrelated to your mod.

**Comment by DakotaPride** [comment]
Okay, just making sure before I close the issue, are there any other questions/feedback that you may want to give in relation to this issue?

**Comment by Sunconure11** [comment]
No.
