### ISSUE TITLE
[ISSUE] Moth wings are invisible from below

### ISSUE THREAD

**Issue by koppiki** [DakotaPride/Pride-Moths#3]
visible from above
![image](https://github.com/DakotaPride/Pride-Moths/assets/96354498/96637d28-37ac-4549-8e15-d08228bed43d)
invisible from below
![image](https://github.com/DakotaPride/Pride-Moths/assets/96354498/f0d55375-2c61-4b65-82ef-01e77e0f5033)

I don't think I have any mods installed that would cull a texture like that?

**Comment by DakotaPride** [comment]
Apologies for the long wait, what MC version are you playing on? This seems to not occur in versions operating in MC 1.20. A modlist would also be appreciated, just in case, but is (of course) hopefully not required to resolve the issue.

**Comment by koppiki** [comment]
> Apologies for the long wait, what MC version are you playing on? This seems to not occur in versions operating in MC 1.20. A modlist would also be appreciated, just in case, but is (of course) hopefully not required to resolve the issue.

oh shoot, I didn't even say the version. my bad! I'm on 1.19.2. I also checked without any mods installed (besides REI, moth, and their dependencies), and the issue was still there. If you still want the modlist I can get it to you, though.

Also, while I'm at it, this moth isn't named:
![image](https://github.com/DakotaPride/Pride-Moths/assets/96354498/8f7cb566-faa6-4baa-819a-d28f785b78ea)

**Comment by DakotaPride** [comment]
The translations should be an easy fix, the model being invisible from certain angles is due to changes in Geckolib's methods/classes. There's also an issue relating to one of the advancements, which should also be fixed in 1.3.2. I'll make sure to let you know when the proper version is released alongside the bugfix!

**Comment by koppiki** [comment]
> The translations should be an easy fix, the model being invisible from certain angles is due to changes in Geckolib's methods/classes. There's also an issue relating to one of the advancements, which should also be fixed in 1.3.2. I'll make sure to let you know when the proper version is released alongside the bugfix!

Thanks a bunch!

**Comment by koppiki** [comment]
Oh, I also forgot to mention that I am specifically using GeckoLib 3.1.40

**Comment by DakotaPride** [comment]
It should now be fixed (hopefully)! The 1.19.2 version is not featured, so you'll have to go into the versions tab on Modrinth in order to actually access the file. Lmk if the issue persists/any other issues arise! thank you for contributing to the project!

**Comment by koppiki** [comment]
Thank you so much! I'm a big fan of these silly little moths.
