### ISSUE TITLE
Issue when placing multiple jars of moths

### ISSUE THREAD

**Issue by AllThatJazz139** [DakotaPride/Pride-Moths#6]
**Describe The Issue**
I attempted to place some moths I picked up in jars that were put into a stack. However, when doing so only one moth was placed and it consumed the stack of moth jars, only leaving me with one empty jar.

**Steps To Reproduce**
[Provide The Potential Steps To Reproduce The Issue]
1. Play on survival mode
2. Give yourself multiple moth jars, or go and collect several moths in jars.
3. Place jars into single stack
4. Shift click ground to place jars.

**Expected Result Of Feature/Implementation**
[Provide An Explanation For The Expected Feature/Implementation]
Either the stack only places one moth and gives back one empty jar, or places all the moths in the stack and gives back all the jars.

**Screenshots**
[If Useful, Provide Screenshots That Could Assist The Situation]
N/A

**Additional Context**
[If Any Additional Context May Be Required, Feel Free To Put It Here]
Minecraft 1.20.1
Pride Moths 1.7
Forge 1.20.1-47.2.17

Tested both in a modpack alongside many other mods, and independently with only pride moths and necessary libraries installed.

**Comment by DakotaPride** [comment]
The item stack size wasn't defined in the forge version for some reason, which caused this issue to occur. Apologies for the inconvenience!

**Comment by DakotaPride** [comment]
The issues mentioned in this report should be fixed now! Let me know if there are any more questions or concerns!
